### ISSUE TITLE
Agregar `ASpli` de Estefanía Mancini

### ISSUE THREAD

**Issue by NPalopoli** [pablotis/asombrosos-paquetes-r-latinoamerica#11]
[ASpli](https://bioconductor.org/packages/release/bioc/html/ASpli.html)

An integrative R package for analysing alternative splicing using RNAseq

Authors: Estefania Mancini, Andrés Rabinovich, Javier Iserte, Marcelo Yanovsky, Ariel Chernomoretz

**Comment by pablotis** [comment]
Hecho, gracias!
