### ISSUE TITLE
Agregar referencia geográfica 

### ISSUE THREAD

**Issue by ldmnch** [pablotis/asombrosos-paquetes-r-latinoamerica#13]
Agregar referencia del país de la fuente de datos, así se pueden buscar los paquetes por ese criterio. Por ejemplo:

Paquete [{casen}](https://github.com/pachadotdev/casen) (Chile). Proporciona un conjunto de funciones para realizar estadistica descriptiva e inferencia con el disenio complejo de la encuesta CASEN.  Autor/es: [M. Vargas](https://github.com/pachadotdev), Kirill Müller

Paquete [{PortalHacienda}](https://github.com/fmgarciadiaz/PortalHacienda-CRAN) (Argentina). Un paquete de interfase a la API del Portal de Datos del Ministerio de Hacienda. Autor/es: [Fernando García Díaz](https://github.com/fmgarciadiaz)

**Comment by pablotis** [comment]
Buena idea! Ahora, el país de la fuente de datos sería sólo para aquellos paquetes de esa temática. Hay paquetes que no tienen una referencia geográfica, se puede agregar el país del o la autora (si es que lo sabemos), quizás? 🤔

**Comment by pablotis** [comment]
Hecho!

![imagen](https://user-images.githubusercontent.com/30708601/204067625-5301fb63-3a48-4100-a486-268f2ad6e5ee.png)
