### ISSUE TITLE
Agregar `sfnetworks` de Lorena Abad

### ISSUE THREAD

**Issue by lindajzmin** [pablotis/asombrosos-paquetes-r-latinoamerica#28]
Hola! He realizado un "pull request" (no sé si estará bien, porque es la segunda vez que lo hago) pero es para sugerirles que incorporen en la lista el paquete  `sfnetworks` desarrollado por Lorena Abad, científica ecuatoriana que actualmente trabaja en Europa.
Saludos,
Linda

**Comment by pablotis** [comment]
Agregado! Mil gracias por el aporte
