### ISSUE TITLE
Agregar codehover de Arthur Wlee

### ISSUE THREAD

**Issue by pablotis** [pablotis/asombrosos-paquetes-r-latinoamerica#29]
https://arthurwelle.github.io/codehover/articles/codehover_intro.html

**Comment by PatriLoto** [comment]
descripción: The codehover aims to make it easy to create a HTML table with a simple hover effect (JavaScript/JQuery + CSS) that shows images just bellow the said table.

Autor: https://github.com/arthurwelle/codehover/

**Comment by pablotis** [comment]
Agregado
