### ISSUE TITLE
Agregar crgeo Manuel Spínola

### ISSUE THREAD

**Issue by ManuelSpinola** [pablotis/asombrosos-paquetes-r-latinoamerica#35]
Repositorio GitHub:

[[]](https://github.com/ManuelSpinola/crgeo)(url)

**Comment by PatriLoto** [comment]
description: The goal of crgeo is to provide geospatial data for Costa Rica.
Autor: Manuel Spínola(https://github.com/ManuelSpinola)
hex: https://github.com/ManuelSpinola/crgeo/blob/master/man/figures/logo.png

**Comment by pablotis** [comment]
Agregado
