### ISSUE TITLE
Agregar concstats Andreas Schneider

### ISSUE THREAD

**Issue by schneiderpy** [pablotis/asombrosos-paquetes-r-latinoamerica#40]
Measures of concentration and competition are important and give a first insight of a given market structure in a particular market. They are important to determine public policies and strategic corporate decisions. However, in research and in practice the most commonly used measure is the Herfindahl Hirschman Index. Various complementary or alternative measures exist, which - used as a set - might reduce uncertainty. The goal of the [concstats](https://cran.r-project.org/package=concstats) package is to offer a set of alternative and/or additional measures for researchers in social sciences and practitioners in institutions concerned with competition on a regular basis to better determine a given market structure and therefore reduce uncertainty with respect to a given market situation. Various functions or groups of functions are available to achieve the desired goal.

https://github.com/ropensci/concstats

**Comment by pablotis** [comment]
Hola @schneiderpy, muchas gracias por hacernos llegar el paquete. Ya lo hemos agregado!

Saludos,
Pablo.

**Comment by schneiderpy** [comment]
Gracias @pablotis
