### ISSUE TITLE
Paquetes a agregar

### ISSUE THREAD

**Issue by pablotis** [pablotis/asombrosos-paquetes-r-latinoamerica#7]
Unheadr luis verde

**Comment by PatriLoto** [comment]
frost de Ana Laura Diedrichs

**Comment by PatriLoto** [comment]
rsppfp de Melina Vidoni (la documentación está en inglés)

**Comment by pablotis** [comment]
@PatriLoto te parece si armamos un issue por cada paquete? así vamos cerrando a medida que sumamos al README 🤔

**Comment by PatriLoto** [comment]
dale si, así queda más ordenado

**Comment by pablotis** [comment]
Perfecto, cierro acá
